{% set name = "quickxorhash" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quickxorhash-{{ version }}.tar.gz
  sha256: 4d0857357bfab95d701ed145beae1fc8d8ac9386aa7475932e82e2afd96a8bb0

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - python
    - setuptools >=46.4.0
    - wheel
    - pip
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - quickxorhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/HarryChen/quickxorhash
  summary: Quick XOR hash function for OneDrive for Business
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - thht
